/**
 * The shape of a receipt.
 *
 * This is the contract between everything that produces receipt data (the
 * Strava flow, the operator's test print, fixtures) and the single renderer
 * that turns it into a bitmap. Nothing downstream of here knows about Strava.
 */

/** A photo, already dithered to 1-bit at `PHOTO_WIDTH`. */
export interface ReceiptPhoto {
  /** PNG data URI. Pure black and white — no greys survive the print anyway. */
  src: string;
  /**
   * Height in print pixels. Width is always `PHOTO_WIDTH`, and the renderer
   * places it at exactly this size: any resampling would smear the dither
   * pattern into mush.
   */
  height: number;
}

/** One itemised label/value row. */
export interface ReceiptStat {
  label: string;
  value: string;
  /**
   * Indented sub-rows print smaller and flush under the row above, the way a
   * real receipt itemises a line. Used for pace / heart rate / elevation.
   */
  indent?: boolean;
}

export interface ReceiptPayload {
  /** Activity name, e.g. "Lunch Run". */
  title: string;
  /** Place line under the title. */
  subtitle?: string;
  /** Long-form date line, e.g. "SATURDAY, AUGUST 3, 2026 AT 7:04 PM". */
  dateLine?: string;
  /** The headline figure — distance, in the reference layout. */
  hero?: {
    /** Column heading above the figure, e.g. "NO. MILES". */
    label: string;
    /** Row heading, e.g. "1 RUN". */
    rowLabel: string;
    /** The number itself, pre-formatted. */
    value: string;
  };
  /** Itemised rows beneath the hero. */
  stats: ReceiptStat[];
  /** Closing total row, printed heavier above the rule. */
  total?: { label: string; value: string; note?: string };
  /** Encoded polyline for the route signature. Omit to drop the section. */
  polyline?: string | null;
  /** Dithered photos, in print order. */
  photos: ReceiptPhoto[];
  /** Extra closing lines above the stamp. */
  footerLines?: readonly string[];
  /** Reported recording device — decides whether Garmin attribution prints. */
  deviceName?: string | null;
  /**
   * Ticket id and timestamp.
   *
   * Generated by the caller, not the renderer, so the PNG the runner previews
   * is byte-identical to the one that prints. The photobooth generated these
   * inside the renderer and had to apologise for clock skew between the two.
   */
  ticket: string;
  stamp: string;
}
